### ISSUE TITLE
Failed to start zcashd

### ISSUE THREAD

**Issue by glestwid** [adityapk00/zecpaperwallet#10]
I downloaded the app from [this link]
[debug.log](https://github.com/adityapk00/zecpaperwallet/files/5156143/debug.log)
(https://github.com/ZcashFoundation/zecwallet/releases/download/v0.9.17/Zecwallet.Fullnode-0.9.17-win.zip), and it threw me the following message upon its the very first start:

> Failed to start zcashd. Giving up! Please look at the debug.log file.
> C:\Users\sengl_000\AppData\Roaming\Zcash/debug.log
> Please file an issue with Zecwallet

Attached you may find the corresponding log file.

**Comment by adityapk00** [comment]
These are the relevant lines from your log:
```
2020-09-01 12:13:43 0 addresses found from DNS seeds
2020-09-01 12:13:43 dnsseed thread exit
```

There seems to be some network issue. Are you on some VPN or otherwise have a unique network situation? I'd try this:

Open Powershell or Command Prompt
```
cd <zecwallet directory>\resources\bin\win
zcashd.exe --addnode=mainnet.z.cash --addnode=lightwalletd.zecwallet.co
```

And see if the daemon starts and syncs. You can then start Zecwallet (while keeping the zcashd.exe running in the terminal window). 

Note that running the fullnode is quite technically intensive, and it can take several days to download and sync. If you want to get started quicker, I'd recommend using the light client from here: www.zecwallet.co
